# Generated by Django 5.1 on 2025-01-16 01:12

import datetime
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('BASICO', 'Basico'), ('BACHILLERATO', 'Bachillerato')], default='INICIAL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paralelo', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(max_length=150)),
                ('apellido_Paterno', models.CharField(max_length=150)),
                ('apellido_Materno', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(max_length=150)),
                ('apellido_Paterno', models.CharField(max_length=150)),
                ('apellido_Materno', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('email_enviado', models.BooleanField(default=False)),
                ('cedula_R1', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres_R1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno_R1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno_R1', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_R1', models.CharField(blank=True, max_length=20, null=True)),
                ('email_R1', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_R1', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('parentesco_R1', models.CharField(blank=True, max_length=50, null=True)),
                ('email_enviado_R1', models.BooleanField(default=False)),
                ('cedula_R2', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres_R2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno_R2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno_R2', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_R2', models.CharField(blank=True, max_length=20, null=True)),
                ('email_R2', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_R2', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('parentesco_R2', models.CharField(blank=True, max_length=50, null=True)),
                ('email_enviado_R2', models.BooleanField(default=False)),
                ('cedula_R3', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres_R3', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno_R3', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno_R3', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_R3', models.CharField(blank=True, max_length=20, null=True)),
                ('email_R3', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_R3', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('parentesco_R3', models.CharField(blank=True, max_length=50, null=True)),
                ('email_enviado_R3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='NINGUNA')),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.asignatura')),
                ('curso_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.curso')),
                ('docente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('cursoAsignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.curso')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.examentrimestral')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNO', max_length=100, null=True)),
                ('aporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.aporte')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='NINGUNA')),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
                ('periodoAcademico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periodoacademico')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='periodoAcademico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.periodoacademico'),
        ),
        migrations.CreateModel(
            name='PeriodoDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periodoacademico')),
            ],
        ),
        migrations.AddField(
            model_name='examentrimestral',
            name='trimestre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision'),
        ),
        migrations.CreateModel(
            name='AsistenciaTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_asistencias', models.PositiveIntegerField(default=0)),
                ('total_atrasos', models.PositiveIntegerField(default=0)),
                ('total_faltas_justificadas', models.PositiveIntegerField(default=0)),
                ('total_faltas_injustificadas', models.PositiveIntegerField(default=0)),
                ('total_asistencias_completas', models.PositiveIntegerField(default=0)),
                ('total_faltas', models.PositiveIntegerField(default=0)),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('periodo_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('ATRASO', 'Atraso'), ('FALTA JUSTIFICADA', 'Falta Justificada'), ('FALTA INJUSTIFICADA', 'Falta Injustificada')], default='ASISTENCIA', max_length=19)),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('periodo_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioPeriodical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioPeriodicalGeneral', models.DecimalField(decimal_places=5, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.curso')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('periodoAcademico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioTrimestres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioTrimestral', models.DecimalField(decimal_places=5, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioTrimestresAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioTrimestral', models.DecimalField(decimal_places=5, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('periodoAcademico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True)),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='subpromedioTipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacionPromedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
                ('tipoEvaluacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.tipoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='EquivalentesTipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioTipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
                ('tipoEvaluacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.tipoevaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='aporte',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.tipoevaluacion'),
        ),
        migrations.CreateModel(
            name='UnidadTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subPromedioUnidad', models.DecimalField(decimal_places=5, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
                ('unidad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.unidadtrimestral')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpromedioTipo', models.DecimalField(decimal_places=5, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('subEquivalenteTipo', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
                ('trimestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.periododivision')),
                ('tipoEvaluacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.tipoevaluacion')),
                ('unidad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.unidadtrimestral')),
            ],
        ),
        migrations.AddField(
            model_name='aporte',
            name='unidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.unidadtrimestral'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Admin'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(max_length=150)),
                ('apellido_Paterno', models.CharField(max_length=150)),
                ('apellido_Materno', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cursoasignatura',
            constraint=models.UniqueConstraint(fields=('asignatura_id', 'curso_id'), name='unique_asignatura_curso'),
        ),
    ]
