# Generated by Django 5.1 on 2025-01-16 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rector', models.CharField(max_length=255)),
                ('fundacion', models.PositiveIntegerField()),
                ('vision', models.TextField()),
                ('mision', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionExamenSupletorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.CharField(blank=True, default='NINGUNA', max_length=100, null=True)),
                ('curso_asignatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.cursoasignatura')),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.examenfinal')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.matricula')),
            ],
        ),
    ]
